# Generated by Django 5.0.1 on 2024-02-27 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_video_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmotionTimestamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotion", models.CharField(max_length=50)),
                ("timestamp", models.FloatField(help_text="Time in seconds")),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.video"
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
