# Generated by Django 5.0.1 on 2024-02-27 18:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_emotiontimestamp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmotionTimestamp",
        ),
    ]
